### ISSUE TITLE
Deeper And Darker bug

### ISSUE THREAD

**Issue by PolThs** [LunaPixelStudios/Better-MC#1034]
### Describe the Bug

when i enter to The Otherside the game crashes, idk what i need to do to replicate the mod, but the game shows me this:
 ---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-02-04 15:04:07
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_5739(net.minecraft.class_1297)" because the return value of "com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.method_6177()" is null
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.method_5773(SculkSnapperEntity.java:127)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1851)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/124472145/216793159-275791ce-2302-45ee-9f55-75577fc03578.png)

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc 1.19.2 v14.5

### Optifine

No

### Other Mods

-Essential mod
-InventoryProfilesNext
-Blockus
-Capybara [Fabric]
-EntityCulling
-Infusion Table
-LiblPN
-mantori
-resses_sodium
-universalbonemeal
-sodium extra
-utilities

**Comment by chorbintime** [comment]
Do not use Essential. We offer no support for it whatsoever, as it is completely unnecessary. Use the serverpack on the modpack page for proper free server hosting.

Entity Culling and Sodium Extra are both already in the modpack.

Update the Deeper Darker mod. If the issue persists, report on their Github.
