### ISSUE TITLE
Minecraft better mc server modpack 1.19.2 v12

### ISSUE THREAD

**Issue by TheReaper20** [LunaPixelStudios/Better-MC#1058]
So recently i have been getting a error while trying to join my own minecraft server the error is Authentication servers are down. Please try again later, sorry! So anyways i can't join the server because of this and when i check the console i can see that http is timing out which makes it harder for mods to register(i think) 
[15:32:27] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.net.http.HttpConnectTimeoutException: HTTP connect timed out
        at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:840) ~[java.net.http:?] {}
        at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?] {}
        at net.minecraftforge.fml.VersionChecker$1.openUrlString(VersionChecker.java:139) ~[fmlcore-1.19.2-43.2.3.jar%23488!/:?] {}
        at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:177) ~[fmlcore-1.19.2-43.2.3.jar%23488!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) [?:?] {re:mixin}
        at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.19.2-43.2.3.jar%23488!/:?] {}
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
        at jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:68) ~[java.net.http:?] {}
        at jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1632) ~[java.net.http:?] {}
        at jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1246) ~[java.net.http:?] {}
Caused by: java.net.ConnectException: HTTP connect timed out
        at jdk.internal.net.http.ResponseTimerEvent.handle(ResponseTimerEvent.java:69) ~[java.net.http:?] {}
        at jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1632) ~[java.net.http:?] {}

if someone can please tell me a solution for this since its getting annoying it started to happen randomly it started 3 days ago

**Comment by chorbintime** [comment]
This is not a modpack issue. Your account is not authenticated properly. It needs to be migrated to Microsoft and you can try logging out then logging back in.
