### ISSUE TITLE
Server freezes when getting this achievement: [Yee hawnted]

### ISSUE THREAD

**Issue by DiamondImp** [LunaPixelStudios/Better-MC#1059]
After my friend and I approached a village in the desert or something like that, he got the achievement above and the server froze. The error in console is the following:

`Failed to handle packet net.minecraft.class_2824@21e59a83, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3966.method_17782()" because "hitResult" is null
        at dev.mrsterner.guardvillagers.GuardVillagers.lambda$onInitialize$0(GuardVillagers.java:62) ~[guard-villagers-fabric-1.19.2-1.0.16.jar:?]
        at net.fabricmc.fabric.api.event.player.UseEntityCallback.lambda$static$0(UseEntityCallback.java:57) ~[fabric-events-interaction-v0-0.4+562bff6e90-2de8d802debc7e46.jar:?]
        at net.minecraft.class_3244$1.handler$cfp000$onPlayerInteractEntity(class_3244.java:1815) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244$1.method_34219(class_3244.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1668) ~[server-intermediary.jar:?]
        at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[server-intermediary.jar:?]
        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by chorbintime** [comment]
Please send the actual crash report file via the mclo.gs website
