### ISSUE TITLE
Kicked from Server: Internal Exception: javalang. RuntimeException: Tried to read NET tag that was too big; tried to allocate: 2097181bytes where max allowed: 2097152

### ISSUE THREAD

**Issue by oracle-of-me** [LunaPixelStudios/Better-MC#1093]
### Describe the Bug

We had issues with this bug in previous Versions of the Modpack. I even posted a bug before.

So this Bug happened again (on the newest Version 15.0). Again, two inventories were deleted. Now the chunks they are building in are broken in a way, that blocks no longer update. No redstone updates, no water flow, Mobs despawning etc. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

15

### Optifine

No

**Comment by chorbintime** [comment]
cant help without logs

**Comment by ThePitereq** [comment]
Had the same problem today.
Just started failing to load chunks.
My error log:
`[15:32:01] [IO-Worker-391/WARN]: Failed to read chunk [111, 66]
java.lang.RuntimeException: Tried to read NBT tag with too high complexity, depth > 512
hundrets of at net.minecraft.class_2487$1.method_23240(class_2487.java:63) ~[server-intermediary.jar:?]
...
java.util.concurrent.CompletionException: java.lang.RuntimeException: Tried to read NBT tag with too high complexity, depth > 512
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at com.mojang.datafixers.util.Either$Right.ifRight(Either.java:109) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.class_3906.method_27917(class_3906.java:29) ~[server-intermediary.jar:?]
	at net.minecraft.class_3906$1.method_16901(class_3906.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.class_4698.method_27939(class_4698.java:236) ~[server-intermediary.jar:?]
	at net.minecraft.class_3847$class_3907.run(class_3847.java:60) [server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) [server-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) [server-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) [server-intermediary.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Tried to read NBT tag with too high complexity, depth > 512
`
`	Line   1696: [04:02:04] [main/ERROR]: Couldn't parse loot table bountiful:blocks/bountyboard <- Last error on server start, just to clarify
	Line   3587: [15:32:01] [IO-Worker-391/ERROR]: Failed to read chunk [111, 66]
	Line   5670: [15:32:13] [IO-Worker-388/ERROR]: Failed to read chunk [227, -103]
	Line   7760: [15:32:27] [IO-Worker-395/ERROR]: Failed to read chunk [119, 66]
	Line   9829: [15:32:27] [IO-Worker-394/ERROR]: Failed to read chunk [116, 66]
	Line  11898: [15:32:27] [IO-Worker-395/ERROR]: Failed to read chunk [116, 65]
	Line  13967: [15:32:27] [IO-Worker-395/ERROR]: Failed to read chunk [118, 65]
	Line  16036: [15:32:27] [IO-Worker-394/ERROR]: Failed to read chunk [120, 65]
	Line  18105: [15:32:27] [IO-Worker-395/ERROR]: Failed to read chunk [122, 68]
	Line  20174: [15:32:27] [IO-Worker-394/ERROR]: Failed to read chunk [122, 71]`
	
We have pillager outpost on chunk [111, 66].
Maybe some pillager got too many NBTs?
![image](https://user-images.githubusercontent.com/61802186/223477906-81d48713-7d6b-40f3-a078-58c3ecdd169e.png)

**Comment by chorbintime** [comment]
update the supplementaries mod
