### ISSUE TITLE
Server Side Installation

### ISSUE THREAD

**Issue by tziady** [LunaPixelStudios/Better-MC#1097]
Hello:

   Looking for any help on the installation server side (Linux) for this mod pack/server. 

   After the start.sh runs, I get some warnings and errors ...

   However, it seems to continue for the most part till it reaches:

`
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.4/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 7 more
Caused by: java.lang.OutOfMemoryError: Java heap space
`
Any help would be appreciated.

Cheers,
T

**Comment by Cyakat** [comment]
It looks like you may being using more memory than your computer allows for. Are you using a VM and, if so, have you allowed your VM enough RAM to run itself and the minecraft server? Usually the default when making a new VM is (1GB).

**Comment by tziady** [comment]
It is a VM that had 2 Gigs. I did recreate the VM with 4 Gigs. However, now, the issue seems to be that it stops at:

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "spark-asyncsampler-worker-thread"
[03:00:10] [Netty Epoll Server IO #1/WARN] [io.ne.ch.ChannelInitializer/]: Failed to initialize a channel. Closing: [id: 0x0459f469, L:/[2600:1f18:6570:6900:d87b:4ca:c40e:8437%0]:25565 - R:/[2601:541:4500:13f1:5a5:8682:d88:501c%0]:50519]
java.lang.OutOfMemoryError: Java heap space
>
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "spark-monitor"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Netty Epoll Server IO #0"
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 827
OpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGWINCH to handler- the VM may need to be forcibly terminated
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 827

Repeating. 

However, this is on an instance with 4Gigs. of memory. 

Any idea what may be causing this?

T

**Comment by tziady** [comment]
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        2.2G        908M        724K        724M        1.4G
Swap:            0B          0B          0B

**Comment by Cyakat** [comment]
It looks like you may still be running out of memory. I went through the README file and it said that 4GB was the minimum recommended. Also remember that the VM OS needs memory too. To be safe, I would try giving the server 6 GB. 
From your `free` command you can see that, without the minecraft server, the OS is already sucking up 2.2GB leaving less than a gig for your server.
Hope this helps!

**Comment by SHXRKIIE** [comment]
We dont test on VM's and so it works on Windows, it says out of memory so we cant do much expect tell you to assign more memory or not use VM's.
