### ISSUE TITLE
Crash on start after updating to V14

### ISSUE THREAD

**Issue by ZubZero619** [LunaPixelStudios/Better-MC#1199]
### Describe the Bug

updatet from V13 to V14
than after that minecraft crashes on starting

--- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-04-30 23:03:49
Description: Initializing game

java.lang.IllegalAccessError: class com.mojang.blaze3d.vertex.BufferBuilder tried to access private field com.mojang.blaze3d.platform.MemoryTracker.f_182525_ (com.mojang.blaze3d.vertex.BufferBuilder and com.mojang.blaze3d.platform.MemoryTracker are in module minecraft@1.19.2 of loader 'TRANSFORMER' @6c835217)
	at com.mojang.blaze3d.vertex.BufferBuilder.release(BufferBuilder.java:4091) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.pipeline.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:APP:mixins.oculus.vertexformat.json:MixinBufferBuilder,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder_SegmentRendering,pl:mixin:APP:immediatelyfast.mixins.json:core.MixinBufferBuilder,pl:mixin:APP:creativecore.mixins.json:BufferBuilderAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.MultiBufferSource.m_109900_(MultiBufferSource.java:546) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:immediatelyfast.mixins.json:core.MixinVertexConsumerProvider,pl:mixin:A}
	at net.minecraft.client.renderer.MultiBufferSource.m_109898_(MultiBufferSource.java:15) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:immediatelyfast.mixins.json:core.MixinVertexConsumerProvider,pl:mixin:A}
	at net.minecraft.client.renderer.OutlineBufferSource.<init>(OutlineBufferSource.java:12) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.RenderBuffers.<init>(RenderBuffers.java:10) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinRenderBuffers,pl:mixin:APP:quark.mixins.json:client.RenderBuffersMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:504) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.8.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.vertex.BufferBuilder.release(BufferBuilder.java:4091) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:rubidium.mixins.json:core.pipeline.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.fast_advance.MixinBufferBuilder,pl:mixin:APP:rubidium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder,pl:mixin:APP:mixins.oculus.vertexformat.json:MixinBufferBuilder,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinBufferBuilder_SegmentRendering,pl:mixin:APP:immediatelyfast.mixins.json:core.MixinBufferBuilder,pl:mixin:APP:creativecore.mixins.json:BufferBuilderAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.MultiBufferSource.m_109900_(MultiBufferSource.java:546) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:immediatelyfast.mixins.json:core.MixinVertexConsumerProvider,pl:mixin:A}
	at net.minecraft.client.renderer.MultiBufferSource.m_109898_(MultiBufferSource.java:15) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:immediatelyfast.mixins.json:core.MixinVertexConsumerProvider,pl:mixin:A}
	at net.minecraft.client.renderer.OutlineBufferSource.<init>(OutlineBufferSource.java:12) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.RenderBuffers.<init>(RenderBuffers.java:10) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,re:classloading,pl:mixin:APP:oculus-batched-entity-rendering.mixins.json:MixinRenderBuffers,pl:mixin:APP:quark.mixins.json:client.RenderBuffersMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:504) ~[client-1.19.2-20220805.130853-srg.jar%23627!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Erweiterte Windows 32 Base-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		AudioDevProps2.dll::2.6.13.0:A-Volute
		AudioDevProps2.dll::2.6.13.0:A-Volute
		AudioSes.dll:Audiositzung:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Bibliothek für Steuerelemente:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Krypto-API32:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.608:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS-Client-API-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL-Hilfsprogrammbibliotheks-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP-Hilfs-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Client-DLL für Windows NT-Basis-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Client-DLL für Windows NT-Basis-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF-Server-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NahimicOSD.dll:NahimicOSD:2.2.23.0:Nahimic
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE für Windows:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.21.1:
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Unterstützungs-DLL für Leistungsdaten:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		ProductInfo.dll
		ProductInfo.dll
		PropSys.dll:Microsoft-Eigenschaftensystem:7.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remoteprozeduraufruf-Laufzeitumgebung:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		SETUPAPI.dll:Windows Setup-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Allgemeine Windows-Shell-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Client-DLL für Windows USER-API (mehrere Benutzer):10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP-Dienste:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.1485 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0-32-Bit-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		antimalware_provider64.dll:AMSI provider :

### Reproduction Steps

1.updating from V13 to V14 via curse forge
2.start game
3.
...

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/132230738/235376221-c16a53bb-8fcc-442f-b793-853bb33393d7.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V14

### Optifine

No

**Comment by chorbintime** [comment]
update your drivers and switch to ATLauncher instead of Curseforge
