### ISSUE TITLE
Cannot connect to a 1.20 V4 server after one disconnect

### ISSUE THREAD

**Issue by AvadaKedavraEagle** [LunaPixelStudios/Better-MC#1309]
### Describe the Bug

Hello, I am having an issue where when if I connect to my server, and then disconnect, I have to restart my client to rejoin. I am quite puzzled. My server has 5gbs of RAM, and the hosting provider is Bisect Hosting.

### Reproduction Steps

1.Join Better MC 1.20 V4 server
2.Disconnect
3.
...

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v4

### Optifine

No

### Other Mods

No

**Comment by SHXRKIIE** [comment]
Dont seem to have the issue myself on v5, can you please update?

**Comment by AvadaKedavraEagle** [comment]
I'll try

**Comment by AvadaKedavraEagle** [comment]
I cannot launch V5. It gives an error, and crashes. [19.07 13:24:18] [Server] [Worker-Main-12/ERROR] [ne.mi.co.ForgeHooks/]: Couldn't parse element loot_tables:bountiful:blocks/bountyboard
[19.07 13:24:18] [Server] com.google.gson.JsonSyntaxExceptionMissing type, expected to find a string
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:127) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.functions.SetContainerContents$Serializer.m_6821_(SetContainerContents.java:112) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.functions.SetContainerContents$Serializer.m_6821_(SetContainerContents.java:101) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction$Serializer.m_7561_(LootItemConditionalFunction.java:99) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction$Serializer.m_7561_(LootItemConditionalFunction.java:88) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:149) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:471) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:192) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:189) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:294) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:291) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:834) ~[forge-1.20.1-47.1.5-universal.jar%23348!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraftforge.common.ForgeHooks.lambda$getLootTableDeserializer$3(ForgeHooks.java:811) ~[forge-1.20.1-47.1.5-universal.jar%23348!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerMixin,pl:mixin:A}
[19.07 13:24:18] [Server] 	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.LootDataManager.m_278660_(LootDataManager.java:55) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:mixin,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinLootDataManager,pl:mixin:APP:puzzleslib.forge.mixins.json:LootDataManagerMixin,pl:mixin:A}
[19.07 13:24:18] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[19.07 13:24:18] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[19.07 13:24:18] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[19.07 13:24:18] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[19.07 13:24:18] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
[19.07 13:24:18] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
[19.07 13:24:18] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
[19.07 13:24:18] [Server] [Worker-Main-12/ERROR] [ne.mi.co.ForgeHooks/]: Couldn't parse element loot_tables:supplementaries:blocks/candle_holder_soul
[19.07 13:24:18] [Server] java.lang.IllegalArgumentExceptionCan't find block supplementaries:candle_holder_soul
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition$Serializer.m_81802_(LootItemBlockStatePropertyCondition.java:79) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition$Serializer.m_7561_(LootItemBlockStatePropertyCondition.java:79) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.predicates.LootItemBlockStatePropertyCondition$Serializer.m_7561_(LootItemBlockStatePropertyCondition.java:68) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction$Serializer.m_7561_(LootItemConditionalFunction.java:98) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction$Serializer.m_7561_(LootItemConditionalFunction.java:88) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading,re:mixin}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:149) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23343!/:?] {re:classloading}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2368!/:?] {}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:18] [Server] 	at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2368!/:?] {re:mixin}
[19.07 13:24:19] [Multicraft] Skipped 124 lines due to rate limit (100/s)
[19.07 13:24:19] [Server] [main/INFO] [minecraft/AdvancementList]: Loaded 4127 advancements
[19.07 13:24:19] [Server] [main/WARN] [co.lo.LootintegrationsMod/]: Parsing loot modifiers for:lootintegrations:dungeonloot_nether with loottable: minecraft:chests/nether_bridge
[19.07 13:24:19] [Server] [main/WARN] [co.lo.LootintegrationsMod/]: Parsing loot modifiers for:lootintegrations:dungeonloot_hard with loottable: minecraft:chests/end_city_treasure
[19.07 13:24:19] [Server] [main/WARN] [co.lo.LootintegrationsMod/]: Parsing loot modifiers for:lootintegrations:dungeonloot_water with loottable: minecraft:chests/underwater_ruin_big
[19.07 13:24:19] [Server] [main/WARN] [co.lo.LootintegrationsMod/]: Parsing loot modifiers for:lootintegrations:dungeonloot_medium with loottable: minecraft:chests/stronghold_crossing
[19.07 13:24:19] [Server] [main/WARN] [co.lo.LootintegrationsMod/]: Parsing loot modifiers for:lootintegrations:villageloot_house with loottable: minecraft:chests/village/village_plains_house
[19.07 13:24:19] [Server] [main/WARN] [co.lo.LootintegrationsMod/]: Parsing loot modifiers for:lootintegrations:dungeonloot_easy with loottable: minecraft:chests/simple_dungeon
[19.07 13:24:19] [Server] [main/WARN] [co.lo.LootintegrationsMod/]: Parsing loot modifiers for:lootintegrations:dungeonloot_no_overflow with loottable: minecraft:chests/simple_dungeon
[19.07 13:24:19] [Server] [main/INFO] [to.th.cu.Curios/]: Loaded 10 curio slots
[19.07 13:24:19] [Server] [main/INFO] [to.th.cu.Curios/]: Loaded 1 curio entities
[19.07 13:24:19] [Server] [main/INFO] [twilightforest/]: Loaded 9 Stalactite configs!
[19.07 13:24:19] [Server] [main/ERROR] [ne.bl.mo.kl.KleeSlabs/]: Slab biomesoplenty:cherry_slab could not be found.
[19.07 13:24:19] [Server] [main/INFO] [Supplementaries/]: Loaded  8 flute songs
[19.07 13:24:19] [Server] [main/INFO] [bountiful/]: Trying to load unloaded files from: config/bountiful/bounty_pools
[19.07 13:24:19] [Server] [main/INFO] [bountiful/]: Trying to load unloaded files from: config/bountiful/bounty_decrees
[19.07 13:24:19] [Server] [main/WARN] [minecraft/MappedRegistry]: Not all defined tags for registry ResourceKey[minecraft:root / minecraft:worldgen/biome] are present in data pack: forge:is_savanna
[19.07 13:24:19] [Server] [main/INFO] [Supplementaries/]: Finished additional setup in 86 ms
[19.07 13:24:19] [Server] Exception in thread "main" java.lang.RuntimeExceptionjava.lang.reflect.InvocationTargetException
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[19.07 13:24:19] [Server] 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[19.07 13:24:19] [Server] Caused byjava.lang.reflect.InvocationTargetException
[19.07 13:24:19] [Server] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19.07 13:24:19] [Server] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[19.07 13:24:19] [Server] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19.07 13:24:19] [Server] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.5/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.5/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.5/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
[19.07 13:24:19] [Server] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[19.07 13:24:19] [Server] 	... more
[19.07 13:24:19] [Server] Caused byjava.lang.NoClassDefFoundError: io/netty/channel/epoll/EpollEventLoopGroup
[19.07 13:24:19] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.<clinit>(ServerConnectionListener.java:54)
[19.07 13:24:19] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:281)
[19.07 13:24:19] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:73)
[19.07 13:24:19] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.lambda$main$4(Main.java:218)
[19.07 13:24:19] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129872_(MinecraftServer.java:260)
[19.07 13:24:19] [Server] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:210)
[19.07 13:24:19] [Server] 	... more
[19.07 13:24:19] [Server] Caused byjava.lang.ClassNotFoundException: io.netty.channel.epoll.EpollEventLoopGroup
[19.07 13:24:19] [Server] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[19.07 13:24:19] [Server] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19.07 13:24:19] [Server] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
[19.07 13:24:19] [Server] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19.07 13:24:19] [Server] 	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
[19.07 13:24:19] [Server] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19.07 13:24:19] [Server] 	... more

**Comment by AvadaKedavraEagle** [comment]
Never mind. I fixed it.
