### ISSUE TITLE
BMC2 V6 HF Not connecting to the server

### ISSUE THREAD

**Issue by xewtra** [LunaPixelStudios/Better-MC#1316]
### Describe the Bug

BMC2 can't connect to server.

Both server and client are running same BMC2 fabric 1.20.1 V6

But at some point connection stops at "joining world" stage and also client console gives a lot of render threads fatal errors (i guess?)
In server's console nothing wrong is happening, it says that [player] joined the game

### Reproduction Steps

1. Connect to the server
2. Wait
3. ???
4. It's not connecting

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/Better-MC/assets/121580878/b23b2495-897f-4f5b-a3d5-5f5b98cf9b3e)
there's much more of such errors

### Crash Report or Log

[21/07/2023 01:11:24 AM] [Render thread/FATAL] Error executing task on Client [21/07/2023 01:11:24 AM] 	at net.minecraft.class_634.method_11132(class_634.java:517) [21/07/2023 01:11:24 AM] 	at net.minecraft.class_2743.method_11817(class_2743.java:47) [21/07/2023 01:11:24 AM] 	at net.minecraft.class_2743.method_11054(class_2743.java:9) [21/07/2023 01:11:24 AM] 	at net.minecraft.class_2600.method_11072(class_2600.java:22) [21/07/2023 01:11:24 AM] 	at net.minecraft.class_1255.method_18859(class_1255.java:156) [21/07/2023 01:11:24 AM] 	at net.minecraft.class_4093.method_18859(class_4093.java:23) [21/07/2023 01:11:24 AM] 	at net.minecraft.class_1255.method_16075(class_1255.java:130) [21/07/2023 01:11:24 AM] 	at net.minecraft.class_1255.method_5383(class_1255.java:115) [21/07/2023 01:11:24 AM] 	at net.minecraft.class_310.method_1523(class_310.java:1175) [21/07/2023 01:11:24 AM] 	at net.minecraft.class_310.method_1514(class_310.java:802) [21/07/2023 01:11:24 AM] 	at net.minecraft.client.main.Main.main(Main.java:250)

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC2 V6 HF

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
How did you install the modpack serverside?

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.

**Comment by xewtra** [comment]
I figured out that i installed server incorrectly, so no problems now, but thanks anyway :)
