### ISSUE TITLE
Fabric Multiplayer v9.5 not working

### ISSUE THREAD

**Issue by HugoSanctorum** [LunaPixelStudios/Better-MC#1368]
### Describe the Bug

Singleplayer does work as intended. But when I try to login to a correctly configured server. The frames doesn't render and let me with "joining world". See the log section for more details

### Reproduction Steps

1. Connect to a multiplayer server with fabric modpack v9.5 
2.
3.
...

### Crash Report or Log

[24/08/2023 23:28:32 PM] 	at net.minecraft.class_634.method_11079(class_634.java:984) [24/08/2023 23:28:32 PM] 	at net.minecraft.class_2761.method_11872(class_2761.java:38) [24/08/2023 23:28:32 PM] 	at net.minecraft.class_2761.method_11054(class_2761.java:6) [24/08/2023 23:28:32 PM] 	at net.minecraft.class_2600.method_11072(class_2600.java:22) [24/08/2023 23:28:32 PM] 	at net.minecraft.class_1255.method_18859(class_1255.java:156) [24/08/2023 23:28:32 PM] 	at net.minecraft.class_4093.method_18859(class_4093.java:23) [24/08/2023 23:28:32 PM] 	at net.minecraft.class_1255.method_16075(class_1255.java:130) [24/08/2023 23:28:32 PM] 	at net.minecraft.class_1255.method_5383(class_1255.java:115) [24/08/2023 23:28:32 PM] 	at net.minecraft.class_310.method_1523(class_310.java:1175) [24/08/2023 23:28:32 PM] 	at net.minecraft.class_310.method_1514(class_310.java:802) [24/08/2023 23:28:32 PM] 	at net.minecraft.client.main.Main.main(Main.java:250) [24/08/2023 23:28:32 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [24/08/2023 23:28:32 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [24/08/2023 23:28:32 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [24/08/2023 23:28:32 PM] [Render thread/FATAL] Error executing task on Client

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

9.5

**Comment by chorbintime** [comment]
please send the actual log file. a snippet doesn't help
