### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by CatLadyAI** [LunaPixelStudios/Better-MC#1437]
### Describe the Bug

Hi I've started experiencing a server crash on startup

```
[11Oct2023 19:50:54.095] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche: 62d66215bcf171c03e09985eee37933be5349f5d rx pkt Short dcid=62d66215bcf171c03e09985eee37933be5349f5d key_phase=false len=21 pn=35 
[11Oct2023 19:50:54.095] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche: 62d66215bcf171c03e09985eee37933be5349f5d rx frm PING
[11Oct2023 19:50:54.095] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche: 62d66215bcf171c03e09985eee37933be5349f5d rx frm PADDING len=3
[11Oct2023 19:50:54.095] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche: 62d66215bcf171c03e09985eee37933be5349f5d tx pkt Short dcid=8a7a1007c2d38fd6 key_phase=false len=5 pn=32 
[11Oct2023 19:50:54.095] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche: 62d66215bcf171c03e09985eee37933be5349f5d tx frm ACK delay=26 blocks=[28..35] ecn_counts=None
[11Oct2023 19:50:54.095] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche::recovery: 62d66215bcf171c03e09985eee37933be5349f5d timer=none latest_rtt=342.646ms srtt=Some(162.001211ms) min_rtt=127.6017ms rttvar=92.104228ms loss_time=[None, None, None] loss_probes=[0, 0, 0] cwnd=12000 ssthresh=18446744073709551615 bytes_in_flight=0 app_limited=true congestion_recovery_start_time=None Rate { delivered: 430, delivered_time: Instant { t: 332.0557564s }, first_sent_time: Instant { t: 332.0557564s }, end_of_app_limited: 25, last_sent_packet: 32, largest_acked: 25, rate_sample: RateSample { delivery_rate: 0, is_app_limited: true, interval: 76.8178503s, delivered: 34, prior_delivered: 396, prior_time: Some(Instant { t: 217.7315228s }), send_elapsed: 0ns, ack_elapsed: 76.8178503s, rtt: 76.8178503s } } pacer=Pacer { enabled: true, capacity: 12000, used: 0, rate: 92591, last_update: Instant { t: 332.0557564s }, next_time: Instant { t: 332.0557564s }, max_datagram_size: 1200, last_packet_size: Some(0), iv: 0ns, max_pacing_rate: None } hystart=window_end=Some(0) last_round_min_rtt=18446744073709551615.999999999s current_round_min_rtt=18446744073709551615.999999999s css_baseline_min_rtt=18446744073709551615.999999999s rtt_sample_count=0 css_start_time=None css_round_count=0 cubic={ k=0 w_max=0 } 
[11Oct2023 19:50:54.791] [Worker-Main-4/ERROR] [ModernFix/]: Async chunk load took way too long, this needs to be reported to the appropriate mod.
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.handler$zbf000$bailIfServerDead(ServerChunkCache.java:2624) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at net.minecraft.world.level.Level.m_6522_(Level.java:187) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at net.minecraft.world.level.Level.m_46865_(Level.java:4043) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at net.minecraftforge.common.extensions.IForgeBlockGetter.getExistingBlockEntity(IForgeBlockGetter.java:39) ~[forge-1.20.1-47.1.47-universal.jar%23468!/:?]
	at xyz.vsngamer.elevatorid.blocks.ElevatorBlock.getElevatorTile(ElevatorBlock.java:288) ~[elevatorid-1.20.1-1.8.15.jar%23334!/:1.20.1-1.8.15]
	at xyz.vsngamer.elevatorid.blocks.ElevatorBlock.m_7753_(ElevatorBlock.java:264) ~[elevatorid-1.20.1-1.8.15.jar%23334!/:1.20.1-1.8.15]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60739_(BlockBehaviour.java:551) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at ca.spottedleaf.starlight.common.light.SkyStarLightEngine.calculateLightValue(SkyStarLightEngine.java:310) ~[starlight-1.1.2+forge.1cda73c.jar%23425!/:1.1.2+forge.1cda73c]
	at ca.spottedleaf.starlight.common.light.StarLightEngine.checkChunkEdge(StarLightEngine.java:530) ~[starlight-1.1.2+forge.1cda73c.jar%23425!/:1.1.2+forge.1cda73c]
	at ca.spottedleaf.starlight.common.light.StarLightEngine.checkChunkEdges(StarLightEngine.java:587) ~[starlight-1.1.2+forge.1cda73c.jar%23425!/:1.1.2+forge.1cda73c]
	at ca.spottedleaf.starlight.common.light.SkyStarLightEngine.checkChunkEdges(SkyStarLightEngine.java:246) ~[starlight-1.1.2+forge.1cda73c.jar%23425!/:1.1.2+forge.1cda73c]
	at ca.spottedleaf.starlight.common.light.StarLightEngine.checkChunkEdges(StarLightEngine.java:863) ~[starlight-1.1.2+forge.1cda73c.jar%23425!/:1.1.2+forge.1cda73c]
	at ca.spottedleaf.starlight.common.light.StarLightInterface.checkSkyEdges(StarLightInterface.java:475) ~[starlight-1.1.2+forge.1cda73c.jar%23425!/:1.1.2+forge.1cda73c]
	at ca.spottedleaf.starlight.common.light.StarLightInterface.checkChunkEdges(StarLightInterface.java:466) ~[starlight-1.1.2+forge.1cda73c.jar%23425!/:1.1.2+forge.1cda73c]
	at net.minecraft.server.level.ThreadedLevelLightEngine.md5416fb$lambda$lightChunk$5$2(ThreadedLevelLightEngine.java:707) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:537) ~[starlight-1.1.2+forge.1cda73c.jar%23425!/:1.1.2+forge.1cda73c]
	at net.minecraft.world.level.lighting.LevelLightEngine.m_9323_(LevelLightEngine.java:599) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at net.minecraft.server.level.ThreadedLevelLightEngine.m_9366_(ThreadedLevelLightEngine.java:187) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at net.minecraft.server.level.ThreadedLevelLightEngine.m_215156_(ThreadedLevelLightEngine.java:166) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[11Oct2023 19:50:59.227] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche: 62d66215bcf171c03e09985eee37933be5349f5d rx pkt Short dcid=62d66215bcf171c03e09985eee37933be5349f5d key_phase=false len=21 pn=36 
[11Oct2023 19:50:59.227] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche: 62d66215bcf171c03e09985eee37933be5349f5d rx frm PING
[11Oct2023 19:50:59.227] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche: 62d66215bcf171c03e09985eee37933be5349f5d rx frm PADDING len=3
[11Oct2023 19:50:59.227] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche: 62d66215bcf171c03e09985eee37933be5349f5d tx pkt Short dcid=8a7a1007c2d38fd6 key_phase=false len=5 pn=33 
[11Oct2023 19:50:59.227] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche: 62d66215bcf171c03e09985eee37933be5349f5d tx frm ACK delay=30 blocks=[28..36] ecn_counts=None
[11Oct2023 19:50:59.227] [nioEventLoopGroup-2-1/DEBUG] [io.netty.incubator.codec.quic.Quiche/]: quiche::recovery: 62d66215bcf171c03e09985eee37933be5349f5d timer=none latest_rtt=342.646ms srtt=Some(162.001211ms) min_rtt=127.6017ms rttvar=92.104228ms loss_time=[None, None, None] loss_probes=[0, 0, 0] cwnd=12000 ssthresh=18446744073709551615 bytes_in_flight=0 app_limited=true congestion_recovery_start_time=None Rate { delivered: 430, delivered_time: Instant { t: 337.1880125s }, first_sent_time: Instant { t: 337.1880125s }, end_of_app_limited: 25, last_sent_packet: 33, largest_acked: 25, rate_sample: RateSample { delivery_rate: 0, is_app_limited: true, interval: 76.8178503s, delivered: 34, prior_delivered: 396, prior_time: Some(Instant { t: 217.7315228s }), send_elapsed: 0ns, ack_elapsed: 76.8178503s, rtt: 76.8178503s } } pacer=Pacer { enabled: true, capacity: 12000, used: 0, rate: 92591, last_update: Instant { t: 337.1880125s }, next_time: Instant { t: 337.1880125s }, max_datagram_size: 1200, last_packet_size: S
```

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

v14

**Comment by chorbintime** [comment]
Remove the starlight mod and report it to the developers of the mod
