### ISSUE TITLE
Forge version mismatch in the server pack

### ISSUE THREAD

**Issue by Duumbo** [LunaPixelStudios/Better-MC#1502]
### Describe the Bug

Hi,
There seems to be a version mismatch of Forge in the server pack v22 of BMC4, 1.20.1
I updated my server from v21 to v22 and got from stdout
```
e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90[02:13:56] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Mod §elmft§r requires §6forge§r §o47.2.6 or above§r
§7Currently, §6forge§r§7 is §o47.2.4
]
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:149) ~[fmlcore-1.20.1-47.2.4.jar%23528!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.2.4-universal.jar%23532!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23527!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.4.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.4.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.4.jar%2369!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```
Looking inside the `librairies/net/minecraftforge/forge`, the java files are named `forge-1.20.1-47.2.4-*.jar`.

### Reproduction Steps

1. Download the server pack from [https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4/files/4905214](the curseforge page).
2. Mark the start script as executable and run.

### Crash Report or Log

https://gist.github.com/Duumbo/bfee2336e75a9e1edf8c5a05f1106b52

### Operating System

Arch Linux

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc v22

### Other Mods

No

**Comment by SHXRKIIE** [comment]
It has the correct forge version, you need to use the v22 serverpack files, not older serverpack files

**Comment by Duumbo** [comment]
Then this should not be how you should update your server? https://www.youtube.com/watch?v=9dLMOiPp_Vk
