### ISSUE TITLE
Bug in Dragon Mounts Legacy causes dragon to be killed

### ISSUE THREAD

**Issue by Meaglin** [LunaPixelStudios/Better-MC#1638]
### Describe the Bug

When you misclick and fall of the dragon the dragon tries to catch you, however there is a bug in the currently used version of the mod that causes and Exception which is caught by the handler that kills the entity (dragon).

It seems the more recent versions of Dragon Mounts Legacy has fixes for this issue and plenty other, could this mod be updated?
( https://github.com/Kay9Unit/Dragon-Mounts-Legacy/pull/185 )

### Reproduction Steps

1. Mount dragon
2. Misclick
3. Fall off
4. Dragon tries to catch and causes Exception
5. Dragon gets killed

### Crash Report or Log

[21Apr2024 14:07:13.897] [Server thread/WARN] [neruina/]: Neruina Caught Exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_20182_()" because "p_20281_" is null
	at net.minecraft.world.entity.Entity.m_20280_(Entity.java:1420) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at com.github.kay9.dragonmounts.dragon.ai.DragonFollowOwnerGoal.m_8045_(DragonFollowOwnerGoal.java:80) ~[dragonmounts-1.20.1-1.1.5.b3.jar%23390!/:1.20.1-1.1.5.b3]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8045_(WrappedGoal.java:27) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:85) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:760) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:128) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.entity.animal.Animal.m_8107_(Animal.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at com.github.kay9.dragonmounts.dragon.TameableDragon.m_8119_(TameableDragon.java:332) ~[dragonmounts-1.20.1-1.1.5.b3.jar%23390!/:1.20.1-1.1.5.b3]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.level.Level.mixinextras$bridge$accept$168(Level.java) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:115) ~[neruina-1.3.0-forge+1.18.2-1.20.1.jar%23465!/:?]
	at net.minecraft.world.level.Level.wrapOperation$bhf000$neruina$catchTickingEntities(Level.java:7040) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23555!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21Apr2024 14:07:13.966] [Server thread/INFO] [net.minecraft.world.entity.LivingEntity/]: Named entity TameableDragon['Naga Draconis'/161818, l='ServerLevel[world]', x=35.40, y=76.49, z=209.10] died: Naga Draconis was killed

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

bmc4 v26

**Comment by chorbintime** [comment]
all mods will be updated in the next modpack update
