### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by sandraveteskova** [LunaPixelStudios/Better-MC#1639]
### Describe the Bug

Hi, i uploaded server pack on my minecraft hosting (fakaheda.eu) server and it keeps shutting down before it even starts, always with the same issue.

_Attempted to load class net/minecraft/client/gui/screens/multiplayer/ServerSelectionList for invalid dist DEDICATED_SERVER_

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

------------------------ **THIS IS CRASH LOG** ------------------------

[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'entity.collisions.unpushable_cramming.EntityPredicatesMixin' as option 'mixin.entity.collisions' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'entity.collisions.unpushable_cramming.EntityTrackingSectionMixin' as option 'mixin.entity.collisions' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'entity.collisions.unpushable_cramming.LivingEntityMixin' as option 'mixin.entity.collisions' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.ServerWorldMixin' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.WorldChunkMixin' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.WorldMixin' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.WrappedBlockEntityTickInvokerAccessor' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.brewing_stand.BrewingStandBlockEntityMixin' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.campfire.CampfireBlockEntityMixin' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.campfire.lit.CampfireBlockEntityMixin' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.campfire.unlit.CampfireBlockEntityMixin' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.furnace.AbstractFurnaceBlockEntityMixin' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.hopper.HopperBlockEntityMixin' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/WARN] [Radium Config/]: Force-disabling mixin 'world.block_entity_ticking.sleeping.shulker_box.ShulkerBoxBlockEntityMixin' as option 'mixin.world.block_entity_ticking.sleeping' (added by user configuration) disables it and children
[19:24:59] [main/INFO] [co.cu.Cupboard/]: Loaded config for: recipeessentials.json
[19:24:59] [main/INFO] [co.cu.Cupboard/]: Loaded config for: structureessentials.json
[19:25:00] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/entity/PhantomRenderer (java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.PhantomRenderer)
[19:25:00] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.entity.PhantomRenderer was not found mixins.deeperdarker.json:PhantomRendererMixin from mod deeperdarker
[19:25:00] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screens/multiplayer/ServerSelectionList for invalid dist DEDICATED_SERVER
[19:25:00] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/screens/multiplayer/ServerSelectionList (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/multiplayer/ServerSelectionList for invalid dist DEDICATED_SERVER)
[19:25:00] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.screens.multiplayer.ServerSelectionList was not found serverbrowser.mixins.json:ServerSelectionMixin from mod serverbrowser
[19:25:00] [main/WARN] [mixin/]: Error loading class: noobanidus/mods/lootr/config/ConfigManager (java.lang.ClassNotFoundException: noobanidus.mods.lootr.config.ConfigManager)
[19:25:00] [main/WARN] [de.to.pa.mi.MixinConfigPlugin/]: For can't fit X into 3 error fix. Delete Krypton or Pluto.
[19:25:00] [main/WARN] [de.to.pa.mi.MixinConfigPlugin/]: For can't fit X into 3 error fix. Delete Krypton or Pluto.
[19:25:00] [main/WARN] [mixin/]: Error loading class: com/mojang/blaze3d/audio/Channel (java.lang.ClassNotFoundException: com.mojang.blaze3d.audio.Channel)
[19:25:00] [main/WARN] [mixin/]: @Mixin target com.mojang.blaze3d.audio.Channel was not found assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ChannelAccessor from mod (unknown)
[19:25:00] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Will be applying 1 memory leak fixes!
[19:25:00] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Currently enabled memory leak fixes: [biomeTemperatureLeak]
[19:25:00] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[19:25:00] [main/WARN] [MixinExtras|Service/]: Found problematic active MixinExtras instance at ca.fxco.memoryleakfix.mixinextras (version 0.2.0-beta.8)
[19:25:00] [main/WARN] [MixinExtras|Service/]: Versions from 0.2.0-beta.1 to 0.2.0-beta.9 have limited support and it is strongly recommended to update.
[19:25:00] [main/INFO] [mixin/]: Mixing server.MixinDedicatedServer from mixins/common/nochatreports.mixins.json into net.minecraft.server.dedicated.DedicatedServer
[19:25:01] [main/INFO] [minecraft/Bootstrap]: ModernFix reached bootstrap stage (16.37 s after launch)
[19:25:01] [main/INFO] [mixin/]: Mixing common.MixinFriendlyByteBuf from mixins/common/nochatreports.mixins.json into net.minecraft.network.FriendlyByteBuf
[19:25:01] [main/INFO] [mixin/]: Renaming synthetic method lambda$onWriteJsonWithCodec$1(Ljava/lang/Object;Ljava/lang/String;)Lio/netty/handler/codec/EncoderException; to mdf7ea89$nochatreports$lambda$onWriteJsonWithCodec$1$0 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf from mod nochatreports
[19:25:01] [main/INFO] [mixin/]: Renaming synthetic method lambda$onReadJsonWithCodec$0(Ljava/lang/String;)Lio/netty/handler/codec/DecoderException; to mdf7ea89$nochatreports$lambda$onReadJsonWithCodec$0$1 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf from mod nochatreports
[19:25:01] [main/INFO] [ModernFix/]: Injecting BlockStateBase cache population hook into getNeighborPathNodeType from me.jellysquid.mods.lithium.mixin.ai.pathing.AbstractBlockStateMixin
[19:25:01] [main/INFO] [ModernFix/]: Injecting BlockStateBase cache population hook into getPathNodeType from me.jellysquid.mods.lithium.mixin.ai.pathing.AbstractBlockStateMixin
[19:25:01] [main/INFO] [ModernFix/]: Injecting BlockStateBase cache population hook into getAllFlags from me.jellysquid.mods.lithium.mixin.util.block_tracking.AbstractBlockStateMixin
[19:25:03] [main/INFO] [minecraft/Bootstrap]: Vanilla bootstrap took 2123 milliseconds
[19:25:03] [main/WARN] [mixin/]: @ModifyConstant conflict. Skipping connectivity.mixins.json:ClientBoundCustomPayloadPacketLMixin from mod connectivity->@ModifyConstant::modifyLimit(I)I with priority 1, already redirected by packetfixer-common.mixins.json:ClientboundCustomPayloadPacketMixin from mod packetfixer->@ModifyConstant::newSize(I)I with priority 9999
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.30/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.30/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.30/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
... 7 more
Caused by: java.lang.ExceptionInInitializerError
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:301)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:121)
... 15 more
Caused by: net.minecraft.ReportedException: Radium Class Analysis
at TRANSFORMER/radium@0.12.2+git.5f80f74/me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.hasMethodOverride(ReflectionUtil.java:36)
at TRANSFORMER/radium@0.12.2+git.5f80f74/me.jellysquid.mods.lithium.common.ai.pathing.BlockClassChecker.lambda$hasNonstandardImplementation$0(BlockClassChecker.java:30)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
at TRANSFORMER/radium@0.12.2+git.5f80f74/me.jellysquid.mods.lithium.common.ai.pathing.BlockClassChecker.shouldUseDynamicTypeCheck(BlockClassChecker.java:22)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Block.handler$zpe000$radium$postConstruct(Block.java:1639)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Block.<init>(Block.java:181)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.CraftingTableBlock.<init>(CraftingTableBlock.java:21)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:241)
... 18 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
at java.base/java.lang.Class.getDeclaredMethod(Class.java:2673)
at TRANSFORMER/radium@0.12.2+git.5f80f74/me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.hasMethodOverride(ReflectionUtil.java:13)
... 25 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method catchTickingItemStack(Lnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/level/Level;Lnet/minecraft/world/entity/Entity;IZLcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)V in neruina-common.mixins.json:PlayerInventoryMixin from mod neruina failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap neruina-common-refmap.json
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
at TRANSFORMER/MixinExtras@0.3.2/com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationInjectionInfo.latePostInject(WrapOperationInjectionInfo.java:76)
at TRANSFORMER/MixinExtras@0.3.2/com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationApplicatorExtension.postApply(WrapOperationApplicatorExtension.java:39)
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.ext.Extensions.postApply(Extensions.java:167)
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.postApply(TargetClassContext.java:432)
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:405)
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
... 42 more
 
 
 

### Crash Report or Log

https://pastebin.com/xi4LEwau

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4

**Comment by chorbintime** [comment]
You need to use the files from the serverpack on the modpack's Curseforge page.
