### ISSUE TITLE
Can't install on server!

### ISSUE THREAD

**Issue by Dm5354** [LunaPixelStudios/Better-MC#699]
I tried to install the modpack on my server and it keeps calling this error!

![image](https://user-images.githubusercontent.com/64665820/188179641-114b88cb-7813-434e-8a42-71e054fc2091.png)

**Comment by xSHXRKIEx** [comment]
I dont myself have linux so I cant really test this but it has worked for other linux users., If it doesnt work just create your own script and install the server from fabric website

**Comment by Dm5354** [comment]
Created a server.jar file with the fabric installer and still crashes, cause missing datapacks!

```
> [Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
> [Pterodactyl Daemon]: Updating process configuration files...
> [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
> container@pterodactyl~ Server marked as starting...
> [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
> [Pterodactyl Daemon]: Finished pulling Docker container image
> === Version Information ===
> openjdk version "17.0.4" 2022-07-19
> OpenJDK Runtime Environment (build 17.0.4+8-Ubuntu-120.04)
> OpenJDK 64-Bit Server VM (build 17.0.4+8-Ubuntu-120.04, mixed mode, sharing)
> ===========================
> :/home/container$ java -Xms512M -Xmx12288M -jar server.jar nogui
> Starting net.minecraft.server.Main
> [14:58:05] [ServerMain/INFO]: Building unoptimized datafixer
> [14:58:06] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
> [14:58:06] [ServerMain/WARN]: Missing data pack Fabric Mods
> [14:58:06] [ServerMain/WARN]: Missing data pack Supplementaries Generated Pack
> [14:58:06] [ServerMain/WARN]: Missing data pack data/Repurposed_Structures-Friends_And_Foes-v2.zip
> [14:58:06] [ServerMain/WARN]: Missing data pack data/Repurposed_Structures-More_Villagers_v7.zip
> [14:58:06] [ServerMain/WARN]: Missing data pack data/dungeons-arise-1-19-v1-1.zip
> [14:58:06] [ServerMain/WARN]: Missing data pack data/ichphilipp-s-endcity-better-end-1-18-1.zip
> [14:58:06] [ServerMain/ERROR]: WorldGenSettings: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/chunk_generator]: bclib:betterx; Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/biome_source]: edenring:biome_source; Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/chunk_generator]: bclib:betterx; Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/chunk_generator]: the_bumblezone:chunk_generator; Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/chunk_generator]: voidz:void missed input: {"edenring:edenring":{generator:{biome_source:{type:"edenring:biome_source"},settings:"minecraft:floating_islands",type:"minecraft:noise"},type:"edenring:edenring"},"minecraft:the_end":{generator:{biome_source:{config:{barrens_biomes_size:256,center_biomes_size:256,generator_version:"paulevs",inner_void_radius_squared:1048576,land_biomes_size:256,map_type:"hex",void_biomes_size:256,with_void_biomes:1b},seed:7926888135652208702L,type:"bclib:end_biome_source"},settings:"minecraft:end",type:"bclib:betterx"},type:"minecraft:the_end"},"minecraft:the_nether":{generator:{biome_source:{config:{biome_size:256,biome_size_vertical:86,map_type:"hex",use_vertical_biomes:1b},seed:7926888135652208702L,type:"bclib:nether_biome_source"},settings:"minecraft:nether",type:"bclib:betterx"},type:"minecraft:the_nether"},"the_bumblezone:the_bumblezone":{generator:{biome_source:{seed:0L,type:"the_bumblezone:biome_source"},settings:"the_bumblezone:bz_noise_settings",type:"the_bumblezone:chunk_generator"},type:"the_bumblezone:the_bumblezone"},"voidz:void":{generator:{type:"voidz:void"},type:"voidz:void_type"}}; Overworld settings missing
> [14:58:06] [ServerMain/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
> java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:dimension_type]: [edenring:edenring, the_bumblezone:the_bumblezone, voidz:void_type]
>         at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
>         at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
>         at net.minecraft.server.Main.main(SourceFile:194) ~[server-1.19.2.jar:?]
>         at net.minecraft.bundler.Main.lambda$run$0(Main.java:54) ~[?:?]
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:dimension_type]: [edenring:edenring, the_bumblezone:the_bumblezone, voidz:void_type]
>         at hh.k(SourceFile:347) ~[server-1.19.2.jar:?]
>         at hn$d.c(SourceFile:128) ~[server-1.19.2.jar:?]
>         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
>         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
>         at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
>         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
>         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
>         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
>         at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
>         at hn$b.<init>(SourceFile:168) ~[server-1.19.2.jar:?]
>         at hn.f(SourceFile:324) ~[server-1.19.2.jar:?]
>         at net.minecraft.server.Main.a(SourceFile:166) ~[server-1.19.2.jar:?]
>         at abt.a(SourceFile:24) ~[server-1.19.2.jar:?]
>         at abu.a(SourceFile:18) ~[server-1.19.2.jar:?]
>         at net.minecraft.server.Main.a(SourceFile:158) ~[server-1.19.2.jar:?]
>         at ad.a(SourceFile:952) ~[server-1.19.2.jar:?]
>         at ad.b(SourceFile:946) ~[server-1.19.2.jar:?]
>         at net.minecraft.server.Main.main(SourceFile:156) ~[server-1.19.2.jar:?]
>         ... 2 more
> container@pterodactyl~ Server marked as offline...
> [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
> [Pterodactyl Daemon]: Exit code: 0
> [Pterodactyl Daemon]: Out of memory: false
> [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
> 

Created the pack first with the PS script then uploaded everything to server, server couldn't launch cos of this:
![image](https://user-images.githubusercontent.com/64665820/188271662-0043d767-22e9-4216-aee8-697ced0eff90.png)

Then created server.jar but now this happens!

**Comment by Dm5354** [comment]
NVM, fixed it!

**Comment by Lalit64** [comment]
@Dm5354 How did you fix it?

**Comment by Lalit64** [comment]
I'm getting the same issue on mac
