### ISSUE TITLE
Server Hosting issue 1.19.2

### ISSUE THREAD

**Issue by colelisiongaming** [LunaPixelStudios/Better-MC#756]
Tested this on two Computers both running windows 11 one with Java 19 One with Java 17 when running the bat file get a output of 

2022-09-22 17:06:43,815 main WARN Advanced terminal features are not available in this environment
[17:06:43] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.1.1, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[17:06:43] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.4.1 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[17:06:44] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Cole%20Smith/OneDrive/Desktop/Better%20MC%20Server%20Pack%20FORGE%201.19.2/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
[17:06:44] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Cole Smith\OneDrive\Desktop\Better MC Server Pack FORGE 1.19.2\libraries\net\minecraftforge\fmlcore\1.19.2-43.1.1\fmlcore-1.19.2-43.1.1.jar is missing mods.toml file
[17:06:44] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Cole Smith\OneDrive\Desktop\Better MC Server Pack FORGE 1.19.2\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.1.1\javafmllanguage-1.19.2-43.1.1.jar is missing mods.toml file
[17:06:44] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Cole Smith\OneDrive\Desktop\Better MC Server Pack FORGE 1.19.2\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.1.1\lowcodelanguage-1.19.2-43.1.1.jar is missing mods.toml file
[17:06:44] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\Cole Smith\OneDrive\Desktop\Better MC Server Pack FORGE 1.19.2\libraries\net\minecraftforge\mclanguage\1.19.2-43.1.1\mclanguage-1.19.2-43.1.1.jar is missing mods.toml file
[17:06:44] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 5 dependencies adding them to mods collection
[17:06:44] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing mandatory dependencies: forge, forge, forge, forge, forge, forge, forge, forge, forge
[17:06:46] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[17:06:46] [main/ERROR] [mixin/]: Mixin config reeses_sodium_options.mixins.json does not specify "minVersion" property
[17:06:46] [main/ERROR] [mixin/]: Mixin config polylib.mixins.json does not specify "minVersion" property
[17:06:46] [main/ERROR] [mixin/]: Mixin config forge-mavm.mixins.json does not specify "minVersion" property
[17:06:46] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.aizistral.nochatreports.MixinConnector]
[17:06:46] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[17:06:46] [main/WARN] [mixin/]: Reference map 'everycomp-common-refmap.json' for everycomp-common.mixins.json could not be read. If this is a development environment you can ignore this message
[17:06:46] [main/WARN] [mixin/]: Reference map 'everycomp.refmap.json' for everycomp.mixins.json could not be read. If this is a development environment you can ignore this message
[17:06:46] [main/INFO] [Canary/]: Loaded configuration file for Canary: 104 options available, 0 override(s) found
[17:06:47] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/entity/PhantomRenderer (java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.PhantomRenderer)
[17:06:47] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.entity.PhantomRenderer was not found deeperdarker.mixins.json:PhantomRendererMixin
[17:06:47] [main/INFO] [mixin/]: Mixing MainMixin from iceberg.mixins.json into net.minecraft.server.Main
[17:06:47] [main/INFO] [mixin/]: Mixing server.MixinDedicatedServer from nochatreports.mixins.json into net.minecraft.server.dedicated.DedicatedServer
[17:06:47] [main/INFO] [Smooth Boot (Reloaded)/]: Smooth Boot (Reloaded) config initialized
[17:06:48] [main/WARN] [mixin/]: @Inject(@At("HEAD")) Shift.BY=1 on blueprint.mixins.json:EntityMixin::handler$zmc001$baseTick exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[17:06:48] [main/INFO] [mixin/]: Mixing server.MixinPlayer from nochatreports.mixins.json into net.minecraft.world.entity.player.Player
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at MC-BOOTSTRAP/fmlloader@1.19.2-43.1.1/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 7 more
Caused by: java.lang.IllegalAccessError: class com.abdelaziz.canary.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (com.abdelaziz.canary.common.shapes.VoxelShapeSimpleCube is in module canary@0.0.2 of loader 'TRANSFORMER' @1e4c6583; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.19.2 of loader 'TRANSFORMER' @1e4c6583)
        at TRANSFORMER/canary@0.0.2/com.abdelaziz.canary.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:31)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.phys.shapes.Shapes.m_166049_(Shapes.java:1601)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.phys.shapes.Shapes.m_83048_(Shapes.java:50)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.phys.shapes.Shapes.<clinit>(Shapes.java:26)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Block.m_49796_(Block.java:140)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.SaplingBlock.<clinit>(SaplingBlock.java:20)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:59)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_224838_(CarverConfiguration.java:20)
        at MC-BOOTSTRAP/datafixerupper@5.0.28/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:16)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:32)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:21)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236012_(BuiltinRegistries.java:53)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236009_(BuiltinRegistries.java:87)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.m_236004_(BuiltinRegistries.java:114)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:113)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.core.Registry.<clinit>(Registry.java:665)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.Main.main(Main.java:110)
        ... 13 more
Press any key to continue . . .

**Comment by chorbintime** [comment]
You aren't supposed to run the .bat. 
You're supposed to run the start.ps1 using Powershell.
