### ISSUE TITLE
Server Crash - Pillagers?

### ISSUE THREAD

**Issue by Deweyoxberg** [LunaPixelStudios/Better-MC#801]
### Describe the Bug

1. Randomly walking around near Pillagers.
2. Server will randomly crash.
3. Server will need full restart as the crash causes a hang.
...

The logs seem to indicate a problem with Pillagers:

Time: 2022-10-18 14:02:50
Description: Accessing LegacyRandomSource from multiple threads

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.util.ThreadingDetector.m_199417_(ThreadingDetector.java:84) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.LegacyRandomSource.m_64707_(LegacyRandomSource.java:49) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.BitRandomSource.m_188503_(BitRandomSource.java:33) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:classloading}
	at net.minecraft.world.entity.monster.Pillager.handler$zce000$addFirework(Pillager.java:529) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,re:classloading,pl:mixin:APP:savage_and_ravage.mixins.json:PillagerMixin,pl:mixin:A}
	at net.minecraft.world.entity.monster.Pillager.m_6518_(Pillager.java) ~[server-1.19.2-20220805.130853-srg.jar%23251!/:?] {re:mixin,re:classloading,pl:mixin:APP:savage_and_ravage.mixins.json:PillagerMixin,pl:mixin:A}
	at com.izofar.takesapillage.world.feature.MobFeature.m_142674_(MobFeature.java:35) ~[takesapillage-1.0.1-1.19.2.jar%23222!/:?] {re:classloading}
	

### Reproduction Steps

1. Randomly walking around near Pillagers.
2. Server will randomly crash.
3. Server will need full restart as the crash causes a hang.
...

### Crash Report or Log

https://pastebin.com/FCMqkYLM

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better Minecraft V7

### Optifine

No

**Comment by chorbintime** [comment]
Report on Savage & Ravage github

**Comment by Deweyoxberg** [comment]
> Report on Savage & Ravage github

Found related issue on named github:

https://github.com/team-abnormals/savage-and-ravage/issues/119
