### ISSUE TITLE
Fabric Server not starting

### ISSUE THREAD

**Issue by DunamisGamer** [LunaPixelStudios/Better-MC#927]
### Describe the Bug

i downloaded the server ran the start.ps1 downloads everything it needs then throws this error.

Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71)
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69)
Caused by: java.lang.RuntimeException: Error invoking MC server bundler: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor.process(BundlerProcessor.java:102)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.locateGame(MinecraftGameProvider.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:177)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	... 1 more
Caused by: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor$1.loadClass(BundlerProcessor.java:65)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.BundlerProcessor.process(BundlerProcessor.java:85)
	... 7 more

### Reproduction Steps

1.download server
2.unzip server
3.run start.ps1 with powershell
4.then the error appears
...

### Screenshots and Videos

![Screenshot (48)](https://user-images.githubusercontent.com/9789397/208307089-fa41b556-61e8-45fd-a455-de8989c85183.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

BMC1

### Optifine

No

**Comment by DunamisGamer** [comment]
Fixed it by installing java 17

**Comment by chorbintime** [comment]
Please read the readme next time
