### ISSUE TITLE
Crashes when starting

### ISSUE THREAD

**Issue by Zlnful** [LunaPixelStudios/Better-MC#963]
Crashes when opening and shows this:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:146)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:210)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing nested jar META-INF/jars/fiber-0.23.0-2.jar from [C:\Users\Max Samuelsson\curseforge\minecraft\Instances\Better MC [FABRIC] - BMC1\mods\collective-fabric-1.19.2-5.16.jar]: java.util.zip.ZipException: invalid distance too far back
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
		at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
		at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
		at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:157)
		... 5 more
	Caused by: java.lang.RuntimeException: Error analyzing nested jar META-INF/jars/fiber-0.23.0-2.jar from [C:\Users\Max Samuelsson\curseforge\minecraft\Instances\Better MC [FABRIC] - BMC1\mods\collective-fabric-1.19.2-5.16.jar]: java.util.zip.ZipException: invalid distance too far back
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:243)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)
		at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
		at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeNestedMods(ModDiscoverer.java:463)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:305)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:253)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)
		at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	Caused by: java.util.zip.ZipException: invalid distance too far back
		at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
		at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
		at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:142)
		at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:120)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarStream(ModDiscoverer.java:357)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:239)
		... 14 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\Max Samuelsson\curseforge\minecraft\Instances\Better MC [FABRIC] - BMC1\mods\collective-fabric-1.19.2-5.16.jar]: java.lang.RuntimeException: Error analyzing nested jar META-INF/jars/fiber-0.23.0-2.jar from [C:\Users\Max Samuelsson\curseforge\minecraft\Instances\Better MC [FABRIC] - BMC1\mods\collective-fabric-1.19.2-5.16.jar]: java.util.zip.ZipException: invalid distance too far back
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562)
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:143)
	... 5 more
Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\Max Samuelsson\curseforge\minecraft\Instances\Better MC [FABRIC] - BMC1\mods\collective-fabric-1.19.2-5.16.jar]: java.lang.RuntimeException: Error analyzing nested jar META-INF/jars/fiber-0.23.0-2.jar from [C:\Users\Max Samuelsson\curseforge\minecraft\Instances\Better MC [FABRIC] - BMC1\mods\collective-fabric-1.19.2-5.16.jar]: java.util.zip.ZipException: invalid distance too far back
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:263)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: [CIRCULAR REFERENCE: java.lang.RuntimeException: Error analyzing nested jar META-INF/jars/fiber-0.23.0-2.jar from [C:\Users\Max Samuelsson\curseforge\minecraft\Instances\Better MC [FABRIC] - BMC1\mods\collective-fabric-1.19.2-5.16.jar]: java.util.zip.ZipException: invalid distance too far back]

**Comment by chorbintime** [comment]
I need an actual crash report file, or post it on mclo.gs

What operating system are you using?

**Comment by SHXRKIIE** [comment]
Either the install failed or you modified the modpack, Id recommend trying another launcher called ATLauncher
