### ISSUE TITLE
Missing or Corrupt chunks

### ISSUE THREAD

**Issue by Briggsy729** [LunaPixelStudios/Better-MC#976]
### Describe the Bug

Running my server locally and having an issue with some chunks not loading right. below is a copy of my server log.
no idea whats causing this or even if it will impact gameplay. 

[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to load chunk ( 2.100E+1  2.100E+1)
java.lang.IllegalArgumentException: Unsupported compression type, must be between 0 and 2 (inclusive)
        at net.creeperhost.ftbbackups.de.piegames.nbt.stream.NBTInputStream.<init>(NBTInputStream.java:159) ~[ftbbackups2-fabric-1.19.2-1.0.17.jar:?]
        at net.creeperhost.ftbbackups.de.piegames.nbt.stream.NBTInputStream.<init>(NBTInputStream.java:111) ~[ftbbackups2-fabric-1.19.2-1.0.17.jar:?]
        at net.creeperhost.ftbbackups.de.piegames.blockmap.renderer.RegionRenderer.renderRaw(RegionRenderer.java:117) ~[ftbbackups2-fabric-1.19.2-1.0.17.jar:?]
        at net.creeperhost.ftbbackups.de.piegames.blockmap.renderer.RegionRenderer.render(RegionRenderer.java:61) ~[ftbbackups2-fabric-1.19.2-1.0.17.jar:?]
        at net.creeperhost.ftbbackups.de.piegames.blockmap.world.RegionFolder$WorldRegionFolder.render(RegionFolder.java:179) ~[ftbbackups2-fabric-1.19.2-1.0.17.jar:?]
        at net.creeperhost.ftbbackups.de.piegames.blockmap.world.RegionFolder$CachedRegionFolder.render(RegionFolder.java:467) ~[ftbbackups2-fabric-1.19.2-1.0.17.jar:?]
        at net.creeperhost.ftbbackups.BackupHandler.createPreview(BackupHandler.java:145) ~[ftbbackups2-fabric-1.19.2-1.0.17.jar:?]
        at net.creeperhost.ftbbackups.BackupHandler.lambda$createBackup$4(BackupHandler.java:250) ~[ftbbackups2-fabric-1.19.2-1.0.17.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (19, 27) section 3. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (27, 2) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (18, 20) section 3. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (22, 19) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (29, 21) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (29, 16) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (31, 10) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (28, 26) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (29, 23) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (31, 3) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (2, 15) section 3. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (25, 3) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (15, 23) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (4, 26) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (3, 28) section 3. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (6, 26) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (5, 29) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (4, 1) section 2. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (5, 28) section 3. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (31, 21) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (15, 21) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (23, 29) section 3. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
*I had to delete a bunch of the log here because it was to long, it was all the same type of lines as above and below*
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (13, 26) section 3. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (11, 28) section 3. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (11, 30) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (11, 31) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (10, 30) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (10, 31) section 4. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:00] [FTB Backups backup thread 0/WARN]: Failed to render chunk (9, 31) section 3. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
java.lang.NullPointerException: null
[17:30:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[17:30:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (twilight_forest): All chunks are saved
[17:30:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (paradise_lost): All chunks are saved
[17:30:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (the_bumblezone): All chunks are saved
[17:30:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:30:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (edenring): All chunks are saved
[17:30:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (void): All chunks are saved
[17:30:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:30:05] [Server thread/INFO]: ThreadedAnvilChunkStorage (otherside): All chunks are saved
[17:30:05] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[17:30:05] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5550ms or 111 ticks behind
[17:30:06] [FTB Backups backup thread 0/INFO]: Setting world minecraft:overworld save state to false
[17:30:06] [FTB Backups backup thread 0/INFO]: Setting world twilightforest:twilight_forest save state to false
[17:30:06] [FTB Backups backup thread 0/INFO]: Setting world paradise_lost:paradise_lost save state to false
[17:30:06] [FTB Backups backup thread 0/INFO]: Setting world the_bumblezone:the_bumblezone save state to false
[17:30:06] [FTB Backups backup thread 0/INFO]: Setting world minecraft:the_nether save state to false
[17:30:06] [FTB Backups backup thread 0/INFO]: Setting world edenring:edenring save state to false
[17:30:06] [FTB Backups backup thread 0/INFO]: Setting world voidz:void save state to false
[17:30:06] [FTB Backups backup thread 0/INFO]: Setting world minecraft:the_end save state to false
[17:30:06] [FTB Backups backup thread 0/INFO]: Setting world deeperdarker:otherside save state to false
[17:30:06] [FTB Backups backup thread 0/INFO]: Backup size 214.3MB World Size 286.9MB
[17:30:06] [FTB Backups backup thread 0/INFO]: Writing to file D:\Games\MINECRAFTMODS\BetterMCFABRICServerPack1.19.2\backups\backups.json
[17:30:06] [FTB Backups backup thread 0/INFO]: New backup created at D:\Games\MINECRAFTMODS\BetterMCFABRICServerPack1.19.2\backups\2023-1-11_17-30-0.zip size: 214.3MB Took: 0m, 6s, 780ms Sha1: 643f4774bc6802cc0016b968d74eb16e961acbd4
[17:30:35] [FTB Backups scheduled executor 0/INFO]: More backups than 5 found, Removing oldest backup
[17:30:35] [FTB Backups scheduled executor 0/INFO]: Removed old backup 2023-1-11_15-0-0.zip
[17:30:35] [FTB Backups scheduled executor 0/INFO]: File missing, removing from backups D:\Games\MINECRAFTMODS\BetterMCFABRICServerPack1.19.2\backups\2023-1-11_15-0-0.zip
[17:30:35] [FTB Backups scheduled executor 0/INFO]: Writing to file D:\Games\MINECRAFTMODS\BetterMCFABRICServerPack1.19.2\backups\backups.json

### Reproduction Steps

1.Not sure how to recreate. seems to be random to me.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19.2
### Modloader

Fabric

### Modpack Version

Better Minecraft Fabric BMC1 Mod pack

### Optifine

I do not use Optifine

### Other Mods

none
![huge_2023-01-11_18 00 11](https://user-images.githubusercontent.com/122500210/211958004-635c76d0-d76c-42c8-ae6e-48a89ed3f78f.png)

**Comment by chorbintime** [comment]
You can find some guides online for what to do about corrupt chunks, its not 100% a modpack issue. A tool like RegionFixer might be what you're looking for.

**Comment by dejl** [comment]
getting this issue as well
I've run regionfixer on the world and it comes up with no chunk errors
Same issue since 12.5, could it be ftbbackups mod?

**Comment by lospejos** [comment]
This may be a related issue:

https://github.com/CreeperHost/FTB-Backups-2/issues/39
