### ISSUE TITLE
Crashes before starting or when Joining World

### ISSUE THREAD

**Issue by PeriFae** [LunaPixelStudios/Better-MC#984]
The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Xaero's Minimap (1.19.1_22.17.0_fabric) has crashed!
Exit Code: -1

**Comment by chorbintime** [comment]
Can't help without the crash report

**Comment by PeriFae** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-01-16 22:52:09
Description: Unexpected error

java.lang.RuntimeException: Xaero's Minimap (1.19.1_22.17.0_fabric) has crashed! Please report here: bit.ly/XaeroMMIssues
	at xaero.common.minimap.MinimapInterface.checkCrashes(MinimapInterface.java:63)
	at xaero.common.minimap.MinimapInterfaceInstance.prePotentialRender(MinimapInterfaceInstance.java:39)
	at xaero.common.interfaces.render.InterfaceRenderer.renderInterfaces(InterfaceRenderer.java:52)
	at xaero.common.events.ForgeEventHandler.handleRenderGameOverlayEventPreOverridable(ForgeEventHandler.java:121)
	at xaero.common.events.ForgeEventHandler.handleRenderGameOverlayEventPre(ForgeEventHandler.java:134)
	at net.minecraft.class_329.handler$jdp000$onRender(class_329.java:13482)
	at net.minecraft.class_329.method_1753(class_329.java:201)
	at net.minecraft.class_757.method_3192(class_757.java:862)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: xaero.common.exception.OpenGLException: OpenGL error: 1282
	at xaero.common.exception.OpenGLException.checkGLError(OpenGLException.java:16)
	at xaero.common.minimap.render.radar.EntityIconPrerenderer.<init>(EntityIconPrerenderer.java:117)
	at xaero.common.minimap.render.MinimapFBORenderer.loadFrameBuffer(MinimapFBORenderer.java:77)
	at xaero.common.minimap.MinimapProcessor.checkFBO(MinimapProcessor.java:130)
	at xaero.common.minimap.MinimapInterfaceInstance.prePotentialRender(MinimapInterfaceInstance.java:33)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at xaero.common.minimap.MinimapInterface.checkCrashes(MinimapInterface.java:63)
	at xaero.common.minimap.MinimapInterfaceInstance.prePotentialRender(MinimapInterfaceInstance.java:39)
	at xaero.common.interfaces.render.InterfaceRenderer.renderInterfaces(InterfaceRenderer.java:52)
	at xaero.common.events.ForgeEventHandler.handleRenderGameOverlayEventPreOverridable(ForgeEventHandler.java:121)
	at xaero.common.events.ForgeEventHandler.handleRenderGameOverlayEventPre(ForgeEventHandler.java:134)
	at net.minecraft.class_329.handler$jdp000$onRender(class_329.java:13482)
	at net.minecraft.class_329.method_1753(class_329.java:201)
Mixins in Stacktrace: None found

-- Affected level --
Details:
	All players: 1 total; [class_746['PeriFae'/1682, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 0, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace: None found

**Comment by chorbintime** [comment]
Set Xaeros Minimap to cpu based rendering in its settings

**Comment by ethbar** [comment]
how do you access the settings for it

**Comment by ethbar** [comment]
where do i find the minimap rendering in setting

**Comment by chorbintime** [comment]
press the xaeros minimap settings keybind

**Comment by Tgoldman123** [comment]
> press the xaeros minimap settings keybind

How should I go about opening the settings keybind if the game is crashing before the world loads in?

**Comment by chorbintime** [comment]
You can access the config both ingame and in the config folder.

**Comment by Tgoldman123** [comment]
I found xaerominimap.txt in the config folder, but I'm not seeing a spot that I could change to something like that. Would you mind telling me if I'm in the correct txt file and what specifically to change? Thank you very much I'm not amazing with this stuff haha

**Comment by chorbintime** [comment]
i'm not 100% sure, it might be best to ask the Xaero's Minimap dev in their Discord

**Comment by thexaero** [comment]
I am 95% certain that this is a case of an Intel Graphics driver bug that I released a workaround fix for a while back. Should be fine in the latest version of the minimap/world map.
